version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  

    steps:
      - checkout  

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            npm install

      - run:
          name: Run linting
          command: |
            flake8            # Lint Python code
            eslint .          # Lint JavaScript code

      - run:
          name: Run tests
          command: |
            pytest            # Run Python tests
            npm test          # Run JavaScript tests

      - run:
          name: Build Docker image
          command: |
            docker build -t my_image .

      - run:
          name: Push Docker image to registry
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker tag my_image $DOCKER_REPO:latest
            docker push $DOCKER_REPO:latest